### ISSUE TITLE
Prodigy Genius won't boot up.

### ISSUE THREAD

**Issue by UltraThyme42** [Toonigy/Prodigen-genius#1]
GET https://toonigy.github.io/Prodigen-genius/1500/js/phaser-spine.min.js net::ERR_ABORTED 404 (Not Found)
1500/:318 
        
        
        GET https://toonigy.github.io/Prodigen-genius/1500/js/phaser.min.js net::ERR_ABORTED 404 (Not Found)
controls.min.js:30    Macaron v2.2.9 | Zendesk Fixes   
public.min.js?v=$webVersion:16  Access to XMLHttpRequest at 'https://web.archive.org/web/20161024145027/https://s3.amazonaws.com/prodigy-assets/education/skills/prod/f08de16886/skillTrees.json' from origin 'https://toonigy.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
send @ public.min.js?v=$webVersion:16
ajax @ public.min.js?v=$webVersion:16
(anonymous) @ question.min.js:13
public.min.js?v=$webVersion:16 
        
        
        GET https://web.archive.org/web/20161024145027/https://s3.amazonaws.com/prodigy-assets/education/skills/prod/f08de16886/skillTrees.json net::ERR_FAILED 302 (Found)
send @ public.min.js?v=$webVersion:16
ajax @ public.min.js?v=$webVersion:16
(anonymous) @ question.min.js:13
public.min.js?v=$webVersion:16  Access to XMLHttpRequest at 'https://web.archive.org/web/20161024145027/https://s3.amazonaws.com/prodigy-assets/education/skills/prod/f08de16886/curricula.json' from origin 'https://toonigy.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
send @ public.min.js?v=$webVersion:16
ajax @ public.min.js?v=$webVersion:16
(anonymous) @ question.min.js:13
public.min.js?v=$webVersion:16 
        
        
        GET https://web.archive.org/web/20161024145027/https://s3.amazonaws.com/prodigy-assets/education/skills/prod/f08de16886/curricula.json net::ERR_FAILED 302 (Found)
send @ public.min.js?v=$webVersion:16
ajax @ public.min.js?v=$webVersion:16
(anonymous) @ question.min.js:13
question.min.js:13    QI v2.2.6 | Student Error Bubbles   
question.min.js:13 {}
question.min.js:13  Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at Prodigy.Curriculum.getCurriculum (question.min.js:13:10184)
    at Prodigy.Curriculum.processSkills (question.min.js:13:9748)
    at Prodigy.SkillSelection.setState (question.min.js:13:13988)
    at new Prodigy.SkillSelection (question.min.js:13:13605)
    at Prodigy.EducationSystem.init (question.min.js:13:11194)
    at new Prodigy.EducationSystem (question.min.js:13:11039)
    at question.min.js:15:13197
    at question.min.js:15:14068
getCurriculum @ question.min.js:13
processSkills @ question.min.js:13
setState @ question.min.js:13
Prodigy.SkillSelection @ question.min.js:13
init @ question.min.js:13
Prodigy.EducationSystem @ question.min.js:13
(anonymous) @ question.min.js:15
(anonymous) @ question.min.js:15
particle-storm.min.js:1  Uncaught ReferenceError: Phaser is not defined
    at particle-storm.min.js:1:1
(anonymous) @ particle-storm.min.js:1
game.min.js:684  Uncaught ReferenceError: Phaser is not defined
    at game.min.js:684:45
(anonymous) @ game.min.js:684
1500/:336  Uncaught TypeError: Cannot read properties of undefined (reading 'init')
    at window.onload (1500/:336:18)

**Comment by Toonigy** [comment]
It's a wip
